model_dir: run/zh-en/

data:
  train_features_file: data/zh-en/train.zh
  train_labels_file: data/zh-en/train.en
  source_vocabulary: data/zh-en/vocab.zh
  target_vocabulary: data/zh-en/vocab.en

inference:
  beam_width: 1              # use GreedySearch (one hypothesis)
  sampling_topp: 0.97         # <== THIS turns on NucleusSampler
  sampling_temperature: 1.5  # optional, can tweak later
