model_type: Transformer
model_dir: runs/enzh-v3/

data:
  train_features_file: data/en-zh-v3/train.en
  train_labels_file: data/en-zh-v3/train.zh
  eval_features_file: data/en-zh-v3/valid.en
  eval_labels_file: data/en-zh-v3/valid.zh
  source_vocabulary: data/en-zh-v3/vocab.en
  target_vocabulary: data/en-zh-v3/vocab.zh